/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Address;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ContactResponse {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("address")
  private Address address = null;
  @SerializedName("primary_email")
  private String primaryEmail = null;
  @SerializedName("alternate_email")
  private String alternateEmail = null;
  @SerializedName("company")
  private String company = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("fax")
  private String fax = null;

  /**
   * Contact name
   **/
  @ApiModelProperty(value = "Contact name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }
  public void setAddress(Address address) {
    this.address = address;
  }

  /**
   * Primary email address. Required.
   **/
  @ApiModelProperty(value = "Primary email address. Required.")
  public String getPrimaryEmail() {
    return primaryEmail;
  }
  public void setPrimaryEmail(String primaryEmail) {
    this.primaryEmail = primaryEmail;
  }

  /**
   * Alternate email address
   **/
  @ApiModelProperty(value = "Alternate email address")
  public String getAlternateEmail() {
    return alternateEmail;
  }
  public void setAlternateEmail(String alternateEmail) {
    this.alternateEmail = alternateEmail;
  }

  /**
   * Company name
   **/
  @ApiModelProperty(value = "Company name")
  public String getCompany() {
    return company;
  }
  public void setCompany(String company) {
    this.company = company;
  }

  /**
   * Phone number. Required.
   **/
  @ApiModelProperty(value = "Phone number. Required.")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * Fax number
   **/
  @ApiModelProperty(value = "Fax number")
  public String getFax() {
    return fax;
  }
  public void setFax(String fax) {
    this.fax = fax;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactResponse contactResponse = (ContactResponse) o;
    return (this.name == null ? contactResponse.name == null : this.name.equals(contactResponse.name)) &&
        (this.address == null ? contactResponse.address == null : this.address.equals(contactResponse.address)) &&
        (this.primaryEmail == null ? contactResponse.primaryEmail == null : this.primaryEmail.equals(contactResponse.primaryEmail)) &&
        (this.alternateEmail == null ? contactResponse.alternateEmail == null : this.alternateEmail.equals(contactResponse.alternateEmail)) &&
        (this.company == null ? contactResponse.company == null : this.company.equals(contactResponse.company)) &&
        (this.phone == null ? contactResponse.phone == null : this.phone.equals(contactResponse.phone)) &&
        (this.fax == null ? contactResponse.fax == null : this.fax.equals(contactResponse.fax));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.primaryEmail == null ? 0: this.primaryEmail.hashCode());
    result = 31 * result + (this.alternateEmail == null ? 0: this.alternateEmail.hashCode());
    result = 31 * result + (this.company == null ? 0: this.company.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.fax == null ? 0: this.fax.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactResponse {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  primaryEmail: ").append(primaryEmail).append("\n");
    sb.append("  alternateEmail: ").append(alternateEmail).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  fax: ").append(fax).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
