/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateMenuParams {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("greeting")
  private Object greeting = null;
  @SerializedName("keypress_error")
  private Object keypressError = null;
  @SerializedName("allow_extension_dial")
  private String allowExtensionDial = null;
  @SerializedName("keypress_wait_time")
  private Integer keypressWaitTime = null;
  @SerializedName("timeout_handler")
  private Object timeoutHandler = null;
  @SerializedName("options")
  private List<Object> options = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getGreeting() {
    return greeting;
  }
  public void setGreeting(Object greeting) {
    this.greeting = greeting;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getKeypressError() {
    return keypressError;
  }
  public void setKeypressError(Object keypressError) {
    this.keypressError = keypressError;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAllowExtensionDial() {
    return allowExtensionDial;
  }
  public void setAllowExtensionDial(String allowExtensionDial) {
    this.allowExtensionDial = allowExtensionDial;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getKeypressWaitTime() {
    return keypressWaitTime;
  }
  public void setKeypressWaitTime(Integer keypressWaitTime) {
    this.keypressWaitTime = keypressWaitTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getTimeoutHandler() {
    return timeoutHandler;
  }
  public void setTimeoutHandler(Object timeoutHandler) {
    this.timeoutHandler = timeoutHandler;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getOptions() {
    return options;
  }
  public void setOptions(List<Object> options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMenuParams createMenuParams = (CreateMenuParams) o;
    return (this.name == null ? createMenuParams.name == null : this.name.equals(createMenuParams.name)) &&
        (this.greeting == null ? createMenuParams.greeting == null : this.greeting.equals(createMenuParams.greeting)) &&
        (this.keypressError == null ? createMenuParams.keypressError == null : this.keypressError.equals(createMenuParams.keypressError)) &&
        (this.allowExtensionDial == null ? createMenuParams.allowExtensionDial == null : this.allowExtensionDial.equals(createMenuParams.allowExtensionDial)) &&
        (this.keypressWaitTime == null ? createMenuParams.keypressWaitTime == null : this.keypressWaitTime.equals(createMenuParams.keypressWaitTime)) &&
        (this.timeoutHandler == null ? createMenuParams.timeoutHandler == null : this.timeoutHandler.equals(createMenuParams.timeoutHandler)) &&
        (this.options == null ? createMenuParams.options == null : this.options.equals(createMenuParams.options));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.greeting == null ? 0: this.greeting.hashCode());
    result = 31 * result + (this.keypressError == null ? 0: this.keypressError.hashCode());
    result = 31 * result + (this.allowExtensionDial == null ? 0: this.allowExtensionDial.hashCode());
    result = 31 * result + (this.keypressWaitTime == null ? 0: this.keypressWaitTime.hashCode());
    result = 31 * result + (this.timeoutHandler == null ? 0: this.timeoutHandler.hashCode());
    result = 31 * result + (this.options == null ? 0: this.options.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMenuParams {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  greeting: ").append(greeting).append("\n");
    sb.append("  keypressError: ").append(keypressError).append("\n");
    sb.append("  allowExtensionDial: ").append(allowExtensionDial).append("\n");
    sb.append("  keypressWaitTime: ").append(keypressWaitTime).append("\n");
    sb.append("  timeoutHandler: ").append(timeoutHandler).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
