/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.CallNotifications;
import io.swagger.client.model.VoicemailInput;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateExtensionParams {
  
  @SerializedName("voicemail")
  private VoicemailInput voicemail = null;
  @SerializedName("call_notifications")
  private CallNotifications callNotifications = null;
  @SerializedName("caller_id")
  private String callerId = null;
  @SerializedName("usage_type")
  private String usageType = null;
  @SerializedName("extension")
  private Integer extension = null;
  @SerializedName("include_in_directory")
  private String includeInDirectory = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("full_name")
  private String fullName = null;
  @SerializedName("timezone")
  private String timezone = null;
  @SerializedName("name_greeting")
  private Object nameGreeting = null;
  @SerializedName("local_area_code")
  private String localAreaCode = null;
  @SerializedName("enable_outbound_calls")
  private String enableOutboundCalls = null;
  @SerializedName("enable_call_waiting")
  private String enableCallWaiting = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public VoicemailInput getVoicemail() {
    return voicemail;
  }
  public void setVoicemail(VoicemailInput voicemail) {
    this.voicemail = voicemail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CallNotifications getCallNotifications() {
    return callNotifications;
  }
  public void setCallNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
  }

  /**
   * Caller ID
   **/
  @ApiModelProperty(value = "Caller ID")
  public String getCallerId() {
    return callerId;
  }
  public void setCallerId(String callerId) {
    this.callerId = callerId;
  }

  /**
   * Extension type
   **/
  @ApiModelProperty(value = "Extension type")
  public String getUsageType() {
    return usageType;
  }
  public void setUsageType(String usageType) {
    this.usageType = usageType;
  }

  /**
   * Extension number (auto-generated if empty)
   **/
  @ApiModelProperty(value = "Extension number (auto-generated if empty)")
  public Integer getExtension() {
    return extension;
  }
  public void setExtension(Integer extension) {
    this.extension = extension;
  }

  /**
   * Include in dial-by-name directory
   **/
  @ApiModelProperty(value = "Include in dial-by-name directory")
  public String getIncludeInDirectory() {
    return includeInDirectory;
  }
  public void setIncludeInDirectory(String includeInDirectory) {
    this.includeInDirectory = includeInDirectory;
  }

  /**
   * Name (auto-generated if empty)
   **/
  @ApiModelProperty(value = "Name (auto-generated if empty)")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Contact name
   **/
  @ApiModelProperty(value = "Contact name")
  public String getFullName() {
    return fullName;
  }
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  /**
   * Timezone
   **/
  @ApiModelProperty(value = "Timezone")
  public String getTimezone() {
    return timezone;
  }
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  /**
   * Recording lookup object
   **/
  @ApiModelProperty(value = "Recording lookup object")
  public Object getNameGreeting() {
    return nameGreeting;
  }
  public void setNameGreeting(Object nameGreeting) {
    this.nameGreeting = nameGreeting;
  }

  /**
   * Local area code
   **/
  @ApiModelProperty(value = "Local area code")
  public String getLocalAreaCode() {
    return localAreaCode;
  }
  public void setLocalAreaCode(String localAreaCode) {
    this.localAreaCode = localAreaCode;
  }

  /**
   * Enable outgoing calls
   **/
  @ApiModelProperty(value = "Enable outgoing calls")
  public String getEnableOutboundCalls() {
    return enableOutboundCalls;
  }
  public void setEnableOutboundCalls(String enableOutboundCalls) {
    this.enableOutboundCalls = enableOutboundCalls;
  }

  /**
   * Enable Call Waiting
   **/
  @ApiModelProperty(value = "Enable Call Waiting")
  public String getEnableCallWaiting() {
    return enableCallWaiting;
  }
  public void setEnableCallWaiting(String enableCallWaiting) {
    this.enableCallWaiting = enableCallWaiting;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateExtensionParams createExtensionParams = (CreateExtensionParams) o;
    return (this.voicemail == null ? createExtensionParams.voicemail == null : this.voicemail.equals(createExtensionParams.voicemail)) &&
        (this.callNotifications == null ? createExtensionParams.callNotifications == null : this.callNotifications.equals(createExtensionParams.callNotifications)) &&
        (this.callerId == null ? createExtensionParams.callerId == null : this.callerId.equals(createExtensionParams.callerId)) &&
        (this.usageType == null ? createExtensionParams.usageType == null : this.usageType.equals(createExtensionParams.usageType)) &&
        (this.extension == null ? createExtensionParams.extension == null : this.extension.equals(createExtensionParams.extension)) &&
        (this.includeInDirectory == null ? createExtensionParams.includeInDirectory == null : this.includeInDirectory.equals(createExtensionParams.includeInDirectory)) &&
        (this.name == null ? createExtensionParams.name == null : this.name.equals(createExtensionParams.name)) &&
        (this.fullName == null ? createExtensionParams.fullName == null : this.fullName.equals(createExtensionParams.fullName)) &&
        (this.timezone == null ? createExtensionParams.timezone == null : this.timezone.equals(createExtensionParams.timezone)) &&
        (this.nameGreeting == null ? createExtensionParams.nameGreeting == null : this.nameGreeting.equals(createExtensionParams.nameGreeting)) &&
        (this.localAreaCode == null ? createExtensionParams.localAreaCode == null : this.localAreaCode.equals(createExtensionParams.localAreaCode)) &&
        (this.enableOutboundCalls == null ? createExtensionParams.enableOutboundCalls == null : this.enableOutboundCalls.equals(createExtensionParams.enableOutboundCalls)) &&
        (this.enableCallWaiting == null ? createExtensionParams.enableCallWaiting == null : this.enableCallWaiting.equals(createExtensionParams.enableCallWaiting));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.voicemail == null ? 0: this.voicemail.hashCode());
    result = 31 * result + (this.callNotifications == null ? 0: this.callNotifications.hashCode());
    result = 31 * result + (this.callerId == null ? 0: this.callerId.hashCode());
    result = 31 * result + (this.usageType == null ? 0: this.usageType.hashCode());
    result = 31 * result + (this.extension == null ? 0: this.extension.hashCode());
    result = 31 * result + (this.includeInDirectory == null ? 0: this.includeInDirectory.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.fullName == null ? 0: this.fullName.hashCode());
    result = 31 * result + (this.timezone == null ? 0: this.timezone.hashCode());
    result = 31 * result + (this.nameGreeting == null ? 0: this.nameGreeting.hashCode());
    result = 31 * result + (this.localAreaCode == null ? 0: this.localAreaCode.hashCode());
    result = 31 * result + (this.enableOutboundCalls == null ? 0: this.enableOutboundCalls.hashCode());
    result = 31 * result + (this.enableCallWaiting == null ? 0: this.enableCallWaiting.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateExtensionParams {\n");
    
    sb.append("  voicemail: ").append(voicemail).append("\n");
    sb.append("  callNotifications: ").append(callNotifications).append("\n");
    sb.append("  callerId: ").append(callerId).append("\n");
    sb.append("  usageType: ").append(usageType).append("\n");
    sb.append("  extension: ").append(extension).append("\n");
    sb.append("  includeInDirectory: ").append(includeInDirectory).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  fullName: ").append(fullName).append("\n");
    sb.append("  timezone: ").append(timezone).append("\n");
    sb.append("  nameGreeting: ").append(nameGreeting).append("\n");
    sb.append("  localAreaCode: ").append(localAreaCode).append("\n");
    sb.append("  enableOutboundCalls: ").append(enableOutboundCalls).append("\n");
    sb.append("  enableCallWaiting: ").append(enableCallWaiting).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
