/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateRedirectUriParams {
  
  @SerializedName("redirect_uri")
  private String redirectUri = null;

  /**
   * Redirect URI string for use in redirect-based flows such as the authorization code and implicit flows
   **/
  @ApiModelProperty(value = "Redirect URI string for use in redirect-based flows such as the authorization code and implicit flows")
  public String getRedirectUri() {
    return redirectUri;
  }
  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRedirectUriParams createRedirectUriParams = (CreateRedirectUriParams) o;
    return (this.redirectUri == null ? createRedirectUriParams.redirectUri == null : this.redirectUri.equals(createRedirectUriParams.redirectUri));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.redirectUri == null ? 0: this.redirectUri.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRedirectUriParams {\n");
    
    sb.append("  redirectUri: ").append(redirectUri).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
