/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.CallNotifications;
import io.swagger.client.model.CallerIdPhoneNumber;
import io.swagger.client.model.SmsForwardingParams;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreatePhoneNumberParams {
  
  @SerializedName("phone_number")
  private Object phoneNumber = null;
  @SerializedName("route")
  private Object route = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("block_incoming")
  private String blockIncoming = null;
  @SerializedName("block_anonymous")
  private String blockAnonymous = null;
  @SerializedName("caller_id")
  private CallerIdPhoneNumber callerId = null;
  @SerializedName("sms_forwarding")
  private SmsForwardingParams smsForwarding = null;
  @SerializedName("call_notifications")
  private CallNotifications callNotifications = null;

  /**
   * Phone number
   **/
  @ApiModelProperty(value = "Phone number")
  public Object getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(Object phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * Route lookup object
   **/
  @ApiModelProperty(value = "Route lookup object")
  public Object getRoute() {
    return route;
  }
  public void setRoute(Object route) {
    this.route = route;
  }

  /**
   * Phone Name
   **/
  @ApiModelProperty(value = "Phone Name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Block incoming calls
   **/
  @ApiModelProperty(value = "Block incoming calls")
  public String getBlockIncoming() {
    return blockIncoming;
  }
  public void setBlockIncoming(String blockIncoming) {
    this.blockIncoming = blockIncoming;
  }

  /**
   * Block anonymous calls
   **/
  @ApiModelProperty(value = "Block anonymous calls")
  public String getBlockAnonymous() {
    return blockAnonymous;
  }
  public void setBlockAnonymous(String blockAnonymous) {
    this.blockAnonymous = blockAnonymous;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CallerIdPhoneNumber getCallerId() {
    return callerId;
  }
  public void setCallerId(CallerIdPhoneNumber callerId) {
    this.callerId = callerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SmsForwardingParams getSmsForwarding() {
    return smsForwarding;
  }
  public void setSmsForwarding(SmsForwardingParams smsForwarding) {
    this.smsForwarding = smsForwarding;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CallNotifications getCallNotifications() {
    return callNotifications;
  }
  public void setCallNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePhoneNumberParams createPhoneNumberParams = (CreatePhoneNumberParams) o;
    return (this.phoneNumber == null ? createPhoneNumberParams.phoneNumber == null : this.phoneNumber.equals(createPhoneNumberParams.phoneNumber)) &&
        (this.route == null ? createPhoneNumberParams.route == null : this.route.equals(createPhoneNumberParams.route)) &&
        (this.name == null ? createPhoneNumberParams.name == null : this.name.equals(createPhoneNumberParams.name)) &&
        (this.blockIncoming == null ? createPhoneNumberParams.blockIncoming == null : this.blockIncoming.equals(createPhoneNumberParams.blockIncoming)) &&
        (this.blockAnonymous == null ? createPhoneNumberParams.blockAnonymous == null : this.blockAnonymous.equals(createPhoneNumberParams.blockAnonymous)) &&
        (this.callerId == null ? createPhoneNumberParams.callerId == null : this.callerId.equals(createPhoneNumberParams.callerId)) &&
        (this.smsForwarding == null ? createPhoneNumberParams.smsForwarding == null : this.smsForwarding.equals(createPhoneNumberParams.smsForwarding)) &&
        (this.callNotifications == null ? createPhoneNumberParams.callNotifications == null : this.callNotifications.equals(createPhoneNumberParams.callNotifications));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    result = 31 * result + (this.route == null ? 0: this.route.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.blockIncoming == null ? 0: this.blockIncoming.hashCode());
    result = 31 * result + (this.blockAnonymous == null ? 0: this.blockAnonymous.hashCode());
    result = 31 * result + (this.callerId == null ? 0: this.callerId.hashCode());
    result = 31 * result + (this.smsForwarding == null ? 0: this.smsForwarding.hashCode());
    result = 31 * result + (this.callNotifications == null ? 0: this.callNotifications.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePhoneNumberParams {\n");
    
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  route: ").append(route).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  blockIncoming: ").append(blockIncoming).append("\n");
    sb.append("  blockAnonymous: ").append(blockAnonymous).append("\n");
    sb.append("  callerId: ").append(callerId).append("\n");
    sb.append("  smsForwarding: ").append(smsForwarding).append("\n");
    sb.append("  callNotifications: ").append(callNotifications).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
