/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FilterVoicemailArray {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("from")
  private String from = null;
  @SerializedName("to")
  private String to = null;
  @SerializedName("is_new")
  private String isNew = null;
  @SerializedName("created_at")
  private Integer createdAt = null;
  @SerializedName("extension")
  private String extension = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFrom() {
    return from;
  }
  public void setFrom(String from) {
    this.from = from;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTo() {
    return to;
  }
  public void setTo(String to) {
    this.to = to;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIsNew() {
    return isNew;
  }
  public void setIsNew(String isNew) {
    this.isNew = isNew;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExtension() {
    return extension;
  }
  public void setExtension(String extension) {
    this.extension = extension;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterVoicemailArray filterVoicemailArray = (FilterVoicemailArray) o;
    return (this.id == null ? filterVoicemailArray.id == null : this.id.equals(filterVoicemailArray.id)) &&
        (this.from == null ? filterVoicemailArray.from == null : this.from.equals(filterVoicemailArray.from)) &&
        (this.to == null ? filterVoicemailArray.to == null : this.to.equals(filterVoicemailArray.to)) &&
        (this.isNew == null ? filterVoicemailArray.isNew == null : this.isNew.equals(filterVoicemailArray.isNew)) &&
        (this.createdAt == null ? filterVoicemailArray.createdAt == null : this.createdAt.equals(filterVoicemailArray.createdAt)) &&
        (this.extension == null ? filterVoicemailArray.extension == null : this.extension.equals(filterVoicemailArray.extension));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.from == null ? 0: this.from.hashCode());
    result = 31 * result + (this.to == null ? 0: this.to.hashCode());
    result = 31 * result + (this.isNew == null ? 0: this.isNew.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.extension == null ? 0: this.extension.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterVoicemailArray {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  from: ").append(from).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("  isNew: ").append(isNew).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  extension: ").append(extension).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
