/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ScopeDetails;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetOauthAccessToken {
  
  @SerializedName("scope")
  private String scope = null;
  @SerializedName("expires_at")
  private Integer expiresAt = null;
  @SerializedName("scope_details")
  private List<ScopeDetails> scopeDetails = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getScope() {
    return scope;
  }
  public void setScope(String scope) {
    this.scope = scope;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getExpiresAt() {
    return expiresAt;
  }
  public void setExpiresAt(Integer expiresAt) {
    this.expiresAt = expiresAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ScopeDetails> getScopeDetails() {
    return scopeDetails;
  }
  public void setScopeDetails(List<ScopeDetails> scopeDetails) {
    this.scopeDetails = scopeDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOauthAccessToken getOauthAccessToken = (GetOauthAccessToken) o;
    return (this.scope == null ? getOauthAccessToken.scope == null : this.scope.equals(getOauthAccessToken.scope)) &&
        (this.expiresAt == null ? getOauthAccessToken.expiresAt == null : this.expiresAt.equals(getOauthAccessToken.expiresAt)) &&
        (this.scopeDetails == null ? getOauthAccessToken.scopeDetails == null : this.scopeDetails.equals(getOauthAccessToken.scopeDetails));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.scope == null ? 0: this.scope.hashCode());
    result = 31 * result + (this.expiresAt == null ? 0: this.expiresAt.hashCode());
    result = 31 * result + (this.scopeDetails == null ? 0: this.scopeDetails.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOauthAccessToken {\n");
    
    sb.append("  scope: ").append(scope).append("\n");
    sb.append("  expiresAt: ").append(expiresAt).append("\n");
    sb.append("  scopeDetails: ").append(scopeDetails).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
