/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * The Listener Object is used to represent a listener. Here are the properties:
 **/
@ApiModel(description = "The Listener Object is used to represent a listener. Here are the properties:")
public class ListenerFull {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("voip_id")
  private Integer voipId = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("event_type")
  private String eventType = null;
  @SerializedName("callbacks")
  private List<Object> callbacks = null;
  @SerializedName("updated_at")
  private Integer updatedAt = null;
  @SerializedName("created_at")
  private Integer createdAt = null;

  /**
   * Integer ID. Read-only.
   **/
  @ApiModelProperty(value = "Integer ID. Read-only.")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getVoipId() {
    return voipId;
  }
  public void setVoipId(Integer voipId) {
    this.voipId = voipId;
  }

  /**
   * Type of listener: callback
   **/
  @ApiModelProperty(value = "Type of listener: callback")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Type of event subscribed by the listener: call.new, call.update, call.complete, call.log, sms.in, sms.out
   **/
  @ApiModelProperty(value = "Type of event subscribed by the listener: call.new, call.update, call.complete, call.log, sms.in, sms.out")
  public String getEventType() {
    return eventType;
  }
  public void setEventType(String eventType) {
    this.eventType = eventType;
  }

  /**
   * Array of Callback Object
   **/
  @ApiModelProperty(value = "Array of Callback Object")
  public List<Object> getCallbacks() {
    return callbacks;
  }
  public void setCallbacks(List<Object> callbacks) {
    this.callbacks = callbacks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Integer updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListenerFull listenerFull = (ListenerFull) o;
    return (this.id == null ? listenerFull.id == null : this.id.equals(listenerFull.id)) &&
        (this.voipId == null ? listenerFull.voipId == null : this.voipId.equals(listenerFull.voipId)) &&
        (this.type == null ? listenerFull.type == null : this.type.equals(listenerFull.type)) &&
        (this.eventType == null ? listenerFull.eventType == null : this.eventType.equals(listenerFull.eventType)) &&
        (this.callbacks == null ? listenerFull.callbacks == null : this.callbacks.equals(listenerFull.callbacks)) &&
        (this.updatedAt == null ? listenerFull.updatedAt == null : this.updatedAt.equals(listenerFull.updatedAt)) &&
        (this.createdAt == null ? listenerFull.createdAt == null : this.createdAt.equals(listenerFull.createdAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.voipId == null ? 0: this.voipId.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.eventType == null ? 0: this.eventType.hashCode());
    result = 31 * result + (this.callbacks == null ? 0: this.callbacks.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListenerFull {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  voipId: ").append(voipId).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  eventType: ").append(eventType).append("\n");
    sb.append("  callbacks: ").append(callbacks).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
