/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * An OAuth Client Full Object is identical as a Summary Object.
 **/
@ApiModel(description = "An OAuth Client Full Object is identical as a Summary Object.")
public class OauthClientFull {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("client_name")
  private String clientName = null;

  /**
   * Client ID
   **/
  @ApiModelProperty(value = "Client ID")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Name of Client
   **/
  @ApiModelProperty(value = "Name of Client")
  public String getClientName() {
    return clientName;
  }
  public void setClientName(String clientName) {
    this.clientName = clientName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OauthClientFull oauthClientFull = (OauthClientFull) o;
    return (this.id == null ? oauthClientFull.id == null : this.id.equals(oauthClientFull.id)) &&
        (this.clientName == null ? oauthClientFull.clientName == null : this.clientName.equals(oauthClientFull.clientName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.clientName == null ? 0: this.clientName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OauthClientFull {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  clientName: ").append(clientName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
