/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OauthAccessToken {
  
  @SerializedName("access_token")
  private String accessToken = null;
  @SerializedName("token_type")
  private String tokenType = null;
  @SerializedName("scope")
  private String scope = null;
  @SerializedName("refresh_token")
  private String refreshToken = null;
  @SerializedName("expires_in")
  private Integer expiresIn = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAccessToken() {
    return accessToken;
  }
  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTokenType() {
    return tokenType;
  }
  public void setTokenType(String tokenType) {
    this.tokenType = tokenType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getScope() {
    return scope;
  }
  public void setScope(String scope) {
    this.scope = scope;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRefreshToken() {
    return refreshToken;
  }
  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getExpiresIn() {
    return expiresIn;
  }
  public void setExpiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OauthAccessToken oauthAccessToken = (OauthAccessToken) o;
    return (this.accessToken == null ? oauthAccessToken.accessToken == null : this.accessToken.equals(oauthAccessToken.accessToken)) &&
        (this.tokenType == null ? oauthAccessToken.tokenType == null : this.tokenType.equals(oauthAccessToken.tokenType)) &&
        (this.scope == null ? oauthAccessToken.scope == null : this.scope.equals(oauthAccessToken.scope)) &&
        (this.refreshToken == null ? oauthAccessToken.refreshToken == null : this.refreshToken.equals(oauthAccessToken.refreshToken)) &&
        (this.expiresIn == null ? oauthAccessToken.expiresIn == null : this.expiresIn.equals(oauthAccessToken.expiresIn));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.accessToken == null ? 0: this.accessToken.hashCode());
    result = 31 * result + (this.tokenType == null ? 0: this.tokenType.hashCode());
    result = 31 * result + (this.scope == null ? 0: this.scope.hashCode());
    result = 31 * result + (this.refreshToken == null ? 0: this.refreshToken.hashCode());
    result = 31 * result + (this.expiresIn == null ? 0: this.expiresIn.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OauthAccessToken {\n");
    
    sb.append("  accessToken: ").append(accessToken).append("\n");
    sb.append("  tokenType: ").append(tokenType).append("\n");
    sb.append("  scope: ").append(scope).append("\n");
    sb.append("  refreshToken: ").append(refreshToken).append("\n");
    sb.append("  expiresIn: ").append(expiresIn).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
