/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.OauthClientFull;
import io.swagger.client.model.RedirectUriFull;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * An OAuth Client Full Object is identical as a Summary Object.
 **/
@ApiModel(description = "An OAuth Client Full Object is identical as a Summary Object.")
public class OauthClientRedirectUriFull {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("client")
  private OauthClientFull client = null;
  @SerializedName("redirect_uri")
  private RedirectUriFull redirectUri = null;

  /**
   * OAuth Client Redirect URI ID
   **/
  @ApiModelProperty(value = "OAuth Client Redirect URI ID")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Client details
   **/
  @ApiModelProperty(value = "Client details")
  public OauthClientFull getClient() {
    return client;
  }
  public void setClient(OauthClientFull client) {
    this.client = client;
  }

  /**
   * Redirect URI details
   **/
  @ApiModelProperty(value = "Redirect URI details")
  public RedirectUriFull getRedirectUri() {
    return redirectUri;
  }
  public void setRedirectUri(RedirectUriFull redirectUri) {
    this.redirectUri = redirectUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OauthClientRedirectUriFull oauthClientRedirectUriFull = (OauthClientRedirectUriFull) o;
    return (this.id == null ? oauthClientRedirectUriFull.id == null : this.id.equals(oauthClientRedirectUriFull.id)) &&
        (this.client == null ? oauthClientRedirectUriFull.client == null : this.client.equals(oauthClientRedirectUriFull.client)) &&
        (this.redirectUri == null ? oauthClientRedirectUriFull.redirectUri == null : this.redirectUri.equals(oauthClientRedirectUriFull.redirectUri));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.client == null ? 0: this.client.hashCode());
    result = 31 * result + (this.redirectUri == null ? 0: this.redirectUri.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OauthClientRedirectUriFull {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  client: ").append(client).append("\n");
    sb.append("  redirectUri: ").append(redirectUri).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
