/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.CallNotifications;
import io.swagger.client.model.Voicemail;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReplaceExtensionParams {
  
  @SerializedName("voicemail")
  private Voicemail voicemail = null;
  @SerializedName("call_notifications")
  private CallNotifications callNotifications = null;
  @SerializedName("name_greeting")
  private Object nameGreeting = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("timezone")
  private String timezone = null;
  @SerializedName("include_in_directory")
  private Boolean includeInDirectory = null;
  @SerializedName("extension")
  private Integer extension = null;
  @SerializedName("enable_outbound_calls")
  private Boolean enableOutboundCalls = null;
  @SerializedName("usage_type")
  private String usageType = null;
  @SerializedName("full_name")
  private String fullName = null;
  @SerializedName("enable_call_waiting")
  private Boolean enableCallWaiting = null;
  @SerializedName("caller_id")
  private String callerId = null;
  @SerializedName("local_area_code")
  private Integer localAreaCode = null;
  @SerializedName("route")
  private String route = null;

  /**
   * Voicemail object
   **/
  @ApiModelProperty(value = "Voicemail object")
  public Voicemail getVoicemail() {
    return voicemail;
  }
  public void setVoicemail(Voicemail voicemail) {
    this.voicemail = voicemail;
  }

  /**
   * Call Notifications object
   **/
  @ApiModelProperty(value = "Call Notifications object")
  public CallNotifications getCallNotifications() {
    return callNotifications;
  }
  public void setCallNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
  }

  /**
   * Recording lookup object
   **/
  @ApiModelProperty(value = "Recording lookup object")
  public Object getNameGreeting() {
    return nameGreeting;
  }
  public void setNameGreeting(Object nameGreeting) {
    this.nameGreeting = nameGreeting;
  }

  /**
   * Name (required)
   **/
  @ApiModelProperty(value = "Name (required)")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Timezone
   **/
  @ApiModelProperty(value = "Timezone")
  public String getTimezone() {
    return timezone;
  }
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  /**
   * Include in dial-by-name directory
   **/
  @ApiModelProperty(value = "Include in dial-by-name directory")
  public Boolean getIncludeInDirectory() {
    return includeInDirectory;
  }
  public void setIncludeInDirectory(Boolean includeInDirectory) {
    this.includeInDirectory = includeInDirectory;
  }

  /**
   * Extension number (required)
   **/
  @ApiModelProperty(value = "Extension number (required)")
  public Integer getExtension() {
    return extension;
  }
  public void setExtension(Integer extension) {
    this.extension = extension;
  }

  /**
   * Enable outgoing calls
   **/
  @ApiModelProperty(value = "Enable outgoing calls")
  public Boolean getEnableOutboundCalls() {
    return enableOutboundCalls;
  }
  public void setEnableOutboundCalls(Boolean enableOutboundCalls) {
    this.enableOutboundCalls = enableOutboundCalls;
  }

  /**
   * Extension type
   **/
  @ApiModelProperty(value = "Extension type")
  public String getUsageType() {
    return usageType;
  }
  public void setUsageType(String usageType) {
    this.usageType = usageType;
  }

  /**
   * Contact name
   **/
  @ApiModelProperty(value = "Contact name")
  public String getFullName() {
    return fullName;
  }
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  /**
   * Enable Call Waiting
   **/
  @ApiModelProperty(value = "Enable Call Waiting")
  public Boolean getEnableCallWaiting() {
    return enableCallWaiting;
  }
  public void setEnableCallWaiting(Boolean enableCallWaiting) {
    this.enableCallWaiting = enableCallWaiting;
  }

  /**
   * Caller ID
   **/
  @ApiModelProperty(value = "Caller ID")
  public String getCallerId() {
    return callerId;
  }
  public void setCallerId(String callerId) {
    this.callerId = callerId;
  }

  /**
   * Local area code
   **/
  @ApiModelProperty(value = "Local area code")
  public Integer getLocalAreaCode() {
    return localAreaCode;
  }
  public void setLocalAreaCode(Integer localAreaCode) {
    this.localAreaCode = localAreaCode;
  }

  /**
   * Route object lookup (must belong to this extension)
   **/
  @ApiModelProperty(value = "Route object lookup (must belong to this extension)")
  public String getRoute() {
    return route;
  }
  public void setRoute(String route) {
    this.route = route;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplaceExtensionParams replaceExtensionParams = (ReplaceExtensionParams) o;
    return (this.voicemail == null ? replaceExtensionParams.voicemail == null : this.voicemail.equals(replaceExtensionParams.voicemail)) &&
        (this.callNotifications == null ? replaceExtensionParams.callNotifications == null : this.callNotifications.equals(replaceExtensionParams.callNotifications)) &&
        (this.nameGreeting == null ? replaceExtensionParams.nameGreeting == null : this.nameGreeting.equals(replaceExtensionParams.nameGreeting)) &&
        (this.name == null ? replaceExtensionParams.name == null : this.name.equals(replaceExtensionParams.name)) &&
        (this.timezone == null ? replaceExtensionParams.timezone == null : this.timezone.equals(replaceExtensionParams.timezone)) &&
        (this.includeInDirectory == null ? replaceExtensionParams.includeInDirectory == null : this.includeInDirectory.equals(replaceExtensionParams.includeInDirectory)) &&
        (this.extension == null ? replaceExtensionParams.extension == null : this.extension.equals(replaceExtensionParams.extension)) &&
        (this.enableOutboundCalls == null ? replaceExtensionParams.enableOutboundCalls == null : this.enableOutboundCalls.equals(replaceExtensionParams.enableOutboundCalls)) &&
        (this.usageType == null ? replaceExtensionParams.usageType == null : this.usageType.equals(replaceExtensionParams.usageType)) &&
        (this.fullName == null ? replaceExtensionParams.fullName == null : this.fullName.equals(replaceExtensionParams.fullName)) &&
        (this.enableCallWaiting == null ? replaceExtensionParams.enableCallWaiting == null : this.enableCallWaiting.equals(replaceExtensionParams.enableCallWaiting)) &&
        (this.callerId == null ? replaceExtensionParams.callerId == null : this.callerId.equals(replaceExtensionParams.callerId)) &&
        (this.localAreaCode == null ? replaceExtensionParams.localAreaCode == null : this.localAreaCode.equals(replaceExtensionParams.localAreaCode)) &&
        (this.route == null ? replaceExtensionParams.route == null : this.route.equals(replaceExtensionParams.route));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.voicemail == null ? 0: this.voicemail.hashCode());
    result = 31 * result + (this.callNotifications == null ? 0: this.callNotifications.hashCode());
    result = 31 * result + (this.nameGreeting == null ? 0: this.nameGreeting.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.timezone == null ? 0: this.timezone.hashCode());
    result = 31 * result + (this.includeInDirectory == null ? 0: this.includeInDirectory.hashCode());
    result = 31 * result + (this.extension == null ? 0: this.extension.hashCode());
    result = 31 * result + (this.enableOutboundCalls == null ? 0: this.enableOutboundCalls.hashCode());
    result = 31 * result + (this.usageType == null ? 0: this.usageType.hashCode());
    result = 31 * result + (this.fullName == null ? 0: this.fullName.hashCode());
    result = 31 * result + (this.enableCallWaiting == null ? 0: this.enableCallWaiting.hashCode());
    result = 31 * result + (this.callerId == null ? 0: this.callerId.hashCode());
    result = 31 * result + (this.localAreaCode == null ? 0: this.localAreaCode.hashCode());
    result = 31 * result + (this.route == null ? 0: this.route.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplaceExtensionParams {\n");
    
    sb.append("  voicemail: ").append(voicemail).append("\n");
    sb.append("  callNotifications: ").append(callNotifications).append("\n");
    sb.append("  nameGreeting: ").append(nameGreeting).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  timezone: ").append(timezone).append("\n");
    sb.append("  includeInDirectory: ").append(includeInDirectory).append("\n");
    sb.append("  extension: ").append(extension).append("\n");
    sb.append("  enableOutboundCalls: ").append(enableOutboundCalls).append("\n");
    sb.append("  usageType: ").append(usageType).append("\n");
    sb.append("  fullName: ").append(fullName).append("\n");
    sb.append("  enableCallWaiting: ").append(enableCallWaiting).append("\n");
    sb.append("  callerId: ").append(callerId).append("\n");
    sb.append("  localAreaCode: ").append(localAreaCode).append("\n");
    sb.append("  route: ").append(route).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
