/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ScopeDetails {
  
  @SerializedName("voip_id")
  private Integer voipId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getVoipId() {
    return voipId;
  }
  public void setVoipId(Integer voipId) {
    this.voipId = voipId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScopeDetails scopeDetails = (ScopeDetails) o;
    return (this.voipId == null ? scopeDetails.voipId == null : this.voipId.equals(scopeDetails.voipId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.voipId == null ? 0: this.voipId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScopeDetails {\n");
    
    sb.append("  voipId: ").append(voipId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
