/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * SMS Forwarding Object, or NULL
 **/
@ApiModel(description = "SMS Forwarding Object, or NULL")
public class SmsForwardingParams {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("extension")
  private Integer extension = null;
  @SerializedName("application")
  private Integer application = null;

  /**
   * Can be \"extension\" or \"application\"
   **/
  @ApiModelProperty(value = "Can be \"extension\" or \"application\"")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Required if type = \"extension\". Extension that messages should be directed to. Output is an Extension Summary Object. Input must be an Extension Lookup Object.
   **/
  @ApiModelProperty(value = "Required if type = \"extension\". Extension that messages should be directed to. Output is an Extension Summary Object. Input must be an Extension Lookup Object.")
  public Integer getExtension() {
    return extension;
  }
  public void setExtension(Integer extension) {
    this.extension = extension;
  }

  /**
   * Required if type = \"application\". Application that messages should be directed to. Output is an Application Summary Object. Input must be an Application Lookup Object.
   **/
  @ApiModelProperty(value = "Required if type = \"application\". Application that messages should be directed to. Output is an Application Summary Object. Input must be an Application Lookup Object.")
  public Integer getApplication() {
    return application;
  }
  public void setApplication(Integer application) {
    this.application = application;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsForwardingParams smsForwardingParams = (SmsForwardingParams) o;
    return (this.type == null ? smsForwardingParams.type == null : this.type.equals(smsForwardingParams.type)) &&
        (this.extension == null ? smsForwardingParams.extension == null : this.extension.equals(smsForwardingParams.extension)) &&
        (this.application == null ? smsForwardingParams.application == null : this.application.equals(smsForwardingParams.application));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.extension == null ? 0: this.extension.hashCode());
    result = 31 * result + (this.application == null ? 0: this.application.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsForwardingParams {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  extension: ").append(extension).append("\n");
    sb.append("  application: ").append(application).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
