/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ExtensionSummary;
import io.swagger.client.model.FromObject;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * The Full Voicemail Object includes all of the properties in the Voicemail Summary Object.
 **/
@ApiModel(description = "The Full Voicemail Object includes all of the properties in the Voicemail Summary Object.")
public class VoicemailFull {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("download_url")
  private String downloadUrl = null;
  @SerializedName("extension")
  private ExtensionSummary extension = null;
  @SerializedName("from")
  private FromObject from = null;
  @SerializedName("to")
  private String to = null;
  @SerializedName("is_new")
  private Boolean isNew = null;
  @SerializedName("created_at")
  private Integer createdAt = null;
  @SerializedName("folder")
  private String folder = null;
  @SerializedName("duration")
  private Integer duration = null;

  /**
   * Unique Voicemail ID. Read-only.
   **/
  @ApiModelProperty(value = "Unique Voicemail ID. Read-only.")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Name. Required.
   **/
  @ApiModelProperty(value = "Name. Required.")
  public String getDownloadUrl() {
    return downloadUrl;
  }
  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  /**
   * Extension where the voicemail is saved into.
   **/
  @ApiModelProperty(value = "Extension where the voicemail is saved into.")
  public ExtensionSummary getExtension() {
    return extension;
  }
  public void setExtension(ExtensionSummary extension) {
    this.extension = extension;
  }

  /**
   * The caller's information
   **/
  @ApiModelProperty(value = "The caller's information")
  public FromObject getFrom() {
    return from;
  }
  public void setFrom(FromObject from) {
    this.from = from;
  }

  /**
   * The phone number where the caller is calling
   **/
  @ApiModelProperty(value = "The phone number where the caller is calling")
  public String getTo() {
    return to;
  }
  public void setTo(String to) {
    this.to = to;
  }

  /**
   * True when Voicemail is new; False when Voicemail has been listened
   **/
  @ApiModelProperty(value = "True when Voicemail is new; False when Voicemail has been listened")
  public Boolean getIsNew() {
    return isNew;
  }
  public void setIsNew(Boolean isNew) {
    this.isNew = isNew;
  }

  /**
   * Date string representing the UTC time that the object was created in the Phone.com API system.
   **/
  @ApiModelProperty(value = "Date string representing the UTC time that the object was created in the Phone.com API system.")
  public Integer getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Folder name where voicemail is saved
   **/
  @ApiModelProperty(value = "Folder name where voicemail is saved")
  public String getFolder() {
    return folder;
  }
  public void setFolder(String folder) {
    this.folder = folder;
  }

  /**
   * Length of voicemail in seconds
   **/
  @ApiModelProperty(value = "Length of voicemail in seconds")
  public Integer getDuration() {
    return duration;
  }
  public void setDuration(Integer duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoicemailFull voicemailFull = (VoicemailFull) o;
    return (this.id == null ? voicemailFull.id == null : this.id.equals(voicemailFull.id)) &&
        (this.downloadUrl == null ? voicemailFull.downloadUrl == null : this.downloadUrl.equals(voicemailFull.downloadUrl)) &&
        (this.extension == null ? voicemailFull.extension == null : this.extension.equals(voicemailFull.extension)) &&
        (this.from == null ? voicemailFull.from == null : this.from.equals(voicemailFull.from)) &&
        (this.to == null ? voicemailFull.to == null : this.to.equals(voicemailFull.to)) &&
        (this.isNew == null ? voicemailFull.isNew == null : this.isNew.equals(voicemailFull.isNew)) &&
        (this.createdAt == null ? voicemailFull.createdAt == null : this.createdAt.equals(voicemailFull.createdAt)) &&
        (this.folder == null ? voicemailFull.folder == null : this.folder.equals(voicemailFull.folder)) &&
        (this.duration == null ? voicemailFull.duration == null : this.duration.equals(voicemailFull.duration));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.downloadUrl == null ? 0: this.downloadUrl.hashCode());
    result = 31 * result + (this.extension == null ? 0: this.extension.hashCode());
    result = 31 * result + (this.from == null ? 0: this.from.hashCode());
    result = 31 * result + (this.to == null ? 0: this.to.hashCode());
    result = 31 * result + (this.isNew == null ? 0: this.isNew.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.folder == null ? 0: this.folder.hashCode());
    result = 31 * result + (this.duration == null ? 0: this.duration.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoicemailFull {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  downloadUrl: ").append(downloadUrl).append("\n");
    sb.append("  extension: ").append(extension).append("\n");
    sb.append("  from: ").append(from).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("  isNew: ").append(isNew).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  folder: ").append(folder).append("\n");
    sb.append("  duration: ").append(duration).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
